package enums;

public enum OutputType {
	POSSESS, POSSESS_WITH_DUPLICATES, DO_NOT_POSSESS, BRIGAND_KING_MINE, BRIGAND_KING_TOTAL,
	BRIGAND_KING_MISSING_MINE, BRIGAND_KING_MISSING_NOT_MINE, BRIGAND_KING_DUPLICATES;
}
